### ISSUE TITLE
Clover configuration.

### ISSUE THREAD

**Issue by elegantcha0s** [cstrouse/Dell-T3610-Hackintosh#2]
Hi, what install configurations did you use for Clover.
Also, should I just copy your EFI folder to my EFI partition in the USB?

Thanks

**Comment by cstrouse** [comment]
I did a vanilla install following the guide for Clover and then upgraded it a few times before rebuilding it from scratch using the dortania guide. You've provided no details about your hardware configuration so you'll need to figure it out for yourself.
