### ISSUE TITLE
What to Change for E5-2660 (non-V) processor

### ISSUE THREAD

**Issue by hassaannaveed** [cstrouse/Dell-T3610-Hackintosh#4]
Hey,
I have the same system but after many attempts I could not install Hackintosh with clover or OC. So, can you plz guide me what do I need to change in your Clover folder for this Processor as it has 8 cores instead of 4: https://ark.intel.com/content/www/us/en/ark/products/64584/intel-xeon-processor-e5-2660-20m-cache-2-20-ghz-8-00-gt-s-intel-qpi.html
Waiting for your Response.
Thanks in Advance

**Comment by cstrouse** [comment]
Are you trying to use the patched ACPI files? They won't work unless your hardware is 100% the same. You should also try disabling `CpuTscSync.kext` in your `config.plist`.

**Comment by hassaannaveed** [comment]
Thanks man. My issue is resolved as I just used the PLUG file instead of your PM file in ACPI files, generated from SSDTTime.
Cheers.
